image: docker:stable

services:
  - docker: dind

stages:
  - docker build and push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_MAGE: gkama/gtk-nlp:latest

docker build and push:
  stage: docker build and push
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_MAGE .
    - docker push $DOCKER_MAGE
  only:
    - master