version: "3.3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mysql:latest"
        environment:
            MYSQL_DATABASE: "nlp"
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306"